import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Land of Shoes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
